FROM golang AS builder
WORKDIR /app

COPY go.* ./
RUN go mod download
COPY *.go ./
RUN go build -o /hello_go_http


FROM golang:1.19.13-alpine3.18
WORKDIR /app
COPY --from=builder /app .
CMD ["/hello_go_http"]
