FROM golang:alpine3.18 AS builder
WORKDIR /app

COPY go.* ./
RUN go mod download
COPY *.go ./
RUN CGO_ENABLED=0 go build -ldflags="-s -w" -o /hello_go_http
RUN rm -rf /app/*

FROM scratch
WORKDIR /app
COPY --from=builder /hello_go_http .
CMD ["./hello_go_http"]